#!/usr/bin/env node

import { execa } from "execa";
import { readFileSync, writeFileSync } from "fs";
import { glob } from "glob";
import { resolve } from "path";
import prettier from "prettier";

async function main() {
    const argv = process.argv.splice(2);

    const command = argv[0];

    const nextConfig = (await import(resolve(process.cwd(), "next.config.js"))).default

    const distDir = resolve(process.cwd(), nextConfig.distDir);
    const prettierConfig = await prettier.resolveConfig(resolve(process.cwd(), ".prettierrc.json"))

    const nextProcess = execa(resolve(process.cwd(), "node_modules", ".bin", "next"), argv, { env: { FORCE_COLOR: "1" } })
    nextProcess.pipeStdout(process.stdout);
    nextProcess.pipeStderr(process.stderr);

    const code = await new Promise((res, rej) => nextProcess.on("exit", (code) => {
        res(code)
    }))

    if (code == 0) {
        if (command == "build") {
            const warningComment = `<!-- This document has been generated by Next.js.\n   - It won't function correctly if you open the .html file into your browser,\n   - instead you should access this page from the web server. -->\n\n`

            const htmlFiles = glob.sync(resolve(distDir, "**", "*.html"));

            for (const html of htmlFiles) {
                let htmlData = readFileSync(html, "utf-8");

                htmlData = htmlData.replace(/\<div class="__html_comment"\>/g, "").replace(/--><\/div>/g, "-->")

                writeFileSync(
                    html,
                    prettier.format(warningComment + htmlData, { ...prettierConfig, parser: "html" })
                )
            }
        }
    }
}

main();